### PR TITLE
Automatic Spawning of Target Area

### PR DESCRIPTION
**Pull request by mhl787156**
image

This PR adds in the area of interest model and adds it to the default fenswood world.

### CODE REVIEW

**Comment by mhl787156** [comment]
@arthurrichards77 new target shape and visuals: 
image

**Comment by mhl787156** [comment]
@arthurrichards77 The new update adds automatic spawning of the target area, along with configuration of all elements from number of spawn points to the min distance between hotspot spawns. 

- Target spawns at a random angle around the center of the 'annulus'.
- Hotspot spawning achieved via sampling theta and radius values from a Normal distribution around the target. 
- Target also fixed to spawn to the right handside of the hill
- Random seed can be set, or target spawn locations can be read in by file. 

Here are some sample spawns: 
image
image
image

**Comment by mhl787156** [comment]
Will merge to master when I get the okay from @arthurrichards77 that this is the correct behaviour!

**Comment by mhl787156** [comment]
Also addresses and closes #9 
Screenshot from 2021-11-09 16-15-42

**Review by rob-clarke — APPROVED** [review]
LGTM. Good commitment on constructing SDF from scratch! I would have done some xacro nonsense

**Comment by mhl787156** [comment]
Awesome, it actually wasn't as bad as It could be, definitely a way to go for generation of simple models. Better than xacro nonsense!

**Pull request merged**
